name: Build Image From Repository URL

on:
  workflow_dispatch:
    inputs:
      clone_url:
        description: 'URL của repository cần clone (vd: https://github.com/user/repo.git)'
        required: true
      image_name:
        description: 'Tên cho image container (vd: my-cool-app)'
        required: true
        default: 'my-app'

      dockerhub_username:
        description: 'Docker Hub Username'
        required: true

      dockerhub_token:
        description: 'Docker Hub Access Token'
        required: true
jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      # Bước 1: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.event.inputs.dockerhub_username }}
          password: ${{ github.event.inputs.dockerhub_token }}

      # Bước 2: Cài đặt pack-cli
      - name: Install pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli
          pack --version
          pack config default-builder heroku/builder:24
          pack builder inspect
          sudo systemctl restart docker
          docker system prune -a -f


 
      # Bước 3: Clone repo cần build
      - name: Clone external repository
        run: git clone ${{ github.event.inputs.clone_url }} ${{ github.event.inputs.image_name }}


      # Bước 4: Build và push image
      - name: Build and push image with Buildpacks
        working-directory: ./${{ github.event.inputs.image_name }}
        run: |
          set -euo pipefail
          export DOCKER_CONFIG="$HOME/.docker"
          IMAGE_NAME=${{ github.event.inputs.dockerhub_username }}/${{ github.event.inputs.image_name }}:latest
          echo "Building and pushing image: $IMAGE_NAME"
          pack build "$IMAGE_NAME" \
            --path . \
            --builder heroku/builder:24 \
            --publish \
            --network host \
            --pull-policy if-not-present
          echo "✅ Build completed successfully."
      # Bước 5: Dọn dẹp  mã nguồn  
      - name:  Display images system
        run: docker images 

      # bước 6: Display pods
      - name: Display pods kubernectes
        run: kubectl get pods

      # bước 7: Clean up
      - name: Clean up cloned repository
        if: always()
        run: | 
         rm -rf ./${{ github.event.inputs.image_name }}
         docker system prune -a -f
         df -h 
         free -h

